// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "gen-cpp/TmServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;
using namespace  ::tserver::gen;

class TmServerHandler : virtual public TmServerIf {
 public:
  TmServerHandler() {
    // Your initialization goes here
  }

  Timestamp time() {
    // Your implementation goes here
    printf("time\n");
    return (0);
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<TmServerHandler> handler(new TmServerHandler());
  shared_ptr<TProcessor> processor(new TmServerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

